apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment
  labels:
    app: hello-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: hello-app
    spec:
      containers:
        - name: hello-app
          image: gauthambappalige12/hello:latest
          ports:
            - containerPort: 8080